const express = require("express");
const router = express.Router();

const meRoutes = require("./me.routes");
const platformRoutes = require("../modules/platform");
const authRoutes = require("../modules/auth/auth.routes");
const shopRoutes = require("./shop.routes");
const productRoutes = require("./product.routes");
const orderRoutes = require("./order.routes");
const adminRoutes = require("./admin.routes");
const paymentRoutes = require("./payment.routes");
const settlementRoutes = require("./settlement.routes");
const shopPayoutRoutes = require("./shop/shop.payout.route");
const inventoryRoutes = require("./inventory.routes");
const reportRoutes = require("../modules/reporting/report.routes");
const settlementAdminRoutes = require("./admin/settlement.routes");
const walletShopRoutes = require("./shop/wallet.routes");
const adminMetricsRoutes = require("./admin.metrics.routes");
const financeAdminRoutes = require("./admin/finance.routes");
const adjustmentAdminRoutes = require("./admin/adjustment.routes");
const complianceAdminRoutes = require("./admin/compliance.routes");
const accountingAdminRoutes = require("./admin/accounting.routes");
const taxAdminRoutes = require("./admin/tax.routes");
const payoutAdminRoutes = require("./admin/payout.routes");
const approvalAdminRoutes = require("./admin/approval.routes");
const healthRoute = require("./health.routes");
const systemRoute = require("../infrastructure/monitoring/health.routes");
const webhookRoutes = require("../infrastructure/webhook/webhook.routes");
const catalogImportRoutes = require("../modules/catalog-import/catalogImport.routes");
const creditRoutes = require("../modules/credit/credit.routes");
const discoveryRoutes = require("../modules/discovery/discovery.routes");
const behaviorRoutes = require("../modules/behavior/behavior.routes");
const catalogRoutes = require("../modules/catalog/catalog.routes");
const supplierMarketplaceRoutes = require("../modules/supplier-marketplace/supplierMarketplace.routes");
const aiInsightsRoutes = require("../modules/ai-insights/aiInsights.routes");
const merchantAssistantRoutes = require("../modules/merchant-assistant/merchantAssistant.routes");
const adsCampaignRoutes = require("../modules/ads/adsCampaign.routes");
const cartRoutes = require("../modules/cart/cart.routes");
const supportRoutes = require("../modules/support/support.routes");

router.use("/", meRoutes);
router.use("/platform", platformRoutes);
router.use("/auth", authRoutes);
router.use("/shops", shopRoutes);
router.use("/products", productRoutes);
router.use("/orders", orderRoutes);
router.use("/payments", paymentRoutes);
router.use("/settlements", settlementRoutes);
router.use("/report", reportRoutes);
router.use("/reports", reportRoutes);
router.use("/dev", require("./dev.routes"));
router.use("/financial-test", require("./financial.test.routes"));

router.use("/shop/payouts", shopPayoutRoutes);
router.use("/shop/wallet", walletShopRoutes);
router.use("/inventory", inventoryRoutes);

router.use("/admin", adminRoutes);
router.use("/admin", adminMetricsRoutes);
router.use("/admin/settlements", settlementAdminRoutes);
router.use("/admin/finance", financeAdminRoutes);
router.use("/admin/adjustments", adjustmentAdminRoutes);
router.use("/admin/compliance", complianceAdminRoutes);
router.use("/admin/accounting", accountingAdminRoutes);
router.use("/admin/taxes", taxAdminRoutes);
router.use("/admin/payouts", payoutAdminRoutes);
router.use("/admin/approval", approvalAdminRoutes);

router.use("/health", healthRoute);
router.use("/system", systemRoute);
router.use("/webhooks", webhookRoutes);

router.use("/catalog", catalogImportRoutes);
router.use("/catalog", catalogRoutes);
router.use("/credit", creditRoutes);
router.use("/search", discoveryRoutes);
router.use("/behavior", behaviorRoutes);
router.use("/suppliers", supplierMarketplaceRoutes);
router.use("/insights", aiInsightsRoutes);
router.use("/assistant", merchantAssistantRoutes);
router.use("/ads", adsCampaignRoutes);
router.use("/cart", cartRoutes);
router.use("/support", supportRoutes);

module.exports = router;
